export const SCHOOLS = [
    "ARIFTS",
    "Campus de Pouillé",
    "CCI",
    "CNAM",
    "CNDC",
    "CNED",
    "Compagnon du Devoir",
    "ECOFAC (groupe)",
    "EEGP",
    "ENSAM",
    "ESA",
    "ESAIP",
    "ESCP Business School",
    "ESEO",
    "ESPL",
    "ESSCA",
    "ESTHUA (Université d'Angers)",
    "ESUP",
    "ETSCO",
    "Groupe alternance",
    "IAE Angers (Université d'Angers)",
    "IFAG école de management et RH",
    "IFEPSA",
    "IFF Europe",
    "IFORIS",
    "IFSI CHU d'Angers",
    "IGC Business School",
    "INSPE",
    "Institut Agro Campus",
    "Institut Mongazon",
    "IPAC business school",
    "IRCOM",
    "IRSS",
    "ISTOM",
    "Jeune travailleur",
    "Lycée Auguste et Jean Renoir",
    "Lycée Chevrollier",
    "Lycée Douanier Rousseau Laval",
    "Lycée Emmanuel Mounier",
    "Lycée Henri Durant",
    "Lycée Jean Bodin",
    "Lycée Jean Moulin",
    "Lycée Joachim du Bellay",
    "Lycée Joseph Wresinski",
    "Lycée le Fresne",
    "Lycée Sacré Coeur la Salle",
    "Lycéen",
    "MBWAY",
    "My Digital School",
    "Oniris VetAgroBio Campus",
    "Polytech Angers (Université d'Angers)",
    "Prépa Défi Pluripass Angers",
    "Saint Aubin la Salle",
    "Service civique",
    "Studio M",
    "TALM",
    "Terrade",
    "Université Catholique de l'Ouest (UCO)",
    "Université d'Angers : Faculté de droit, économie et gestion",
    "Université d'Angers : Faculté de lettres, langues et sciences humaines",
    "Université d'Angers : Faculté de santé",
    "Université d'Angers : Faculté de sciences",
    "WIN",
    "Autre"
];