export const SCHOOLS = [
    "ARIFTS",
    "Campus de Pouillé",
    "CCI",
    "CNAM",
    "CNDC",
    "CNED",
    "Compagnon du Devoir",
    "ECOFAC (groupe)",
    "EEGP",
    "ENSAM",
    "ESA",
    "ESAIP",
    "ESCP Business School",
    "ESEO",
    "ESPL",
    "ESUP",
    "ESSCA",
    "ESTHUA",
    "ETSCO",
    "Groupe alternance",
    "IFAG école de management et RH",
    "IFEPSA",
    "IFF Europe",
    "IFORIS",
    "IFSI CHU d'Angers",
    "IGC Business School",
    "INSPE",
    "Institut Agro Campus",
    "Institut Mongazon",
    "IPAC business school",
    "ISTOM",
    "IRCOM",
    "IRSS",
    "Lycée Auguste et Jean Renoir",
    "Lycée Chevrollier",
    "Lycée Douanier Rousseau Laval",
    "Lycée Emmanuel Mounier",
    "Lycée Henri Durant",
    "Lycée le Fresne",
    "Lycée Jean Bodin",
    "Lycée Jean Moulin",
    "Lycée Joachim du Bellay",
    "Lycée Joseph Wresinski",
    "Lycée Sacré Coeur la Salle",
    "Lycéen",
    "Jeune travailleur",
    "MBWAY",
    "My Digital School",
    "Oniris VetAgroBio Campus",
    "Polytech",
    "Prépa Défi Pluripass Angers",
    "TALM",
    "Terrade",
    "Saint Aubin la Salle",
    "Service civique",
    "Studio M",
    "Université Catholique de l'Ouest",
    "Université d'Angers (Belle Beille, Saint Serge, Santé, etc)",
    "WIN",
    "Autre"
];
